### ISSUE TITLE
3d secure対応に伴うAPIの増加

### ISSUE THREAD

**Issue by araera111** [nemuvski/typedef-payjp-js#1]
このライブラリを便利に使っています。ありがとうございます。

3d secureの対応に伴い、APIがいろいろ増えているようです。

### Payjpのインスタンス初期化時のoption
Payjp(publicKey: string, options?: object)
options -> threeDSecureWorkflow

### createToken時に渡せるOption

create token
```ts
	export type TokenOptions = {
		card: Partial<{
			address_state: string;
			address_city: string;
			address_line1: string;
			address_line2: string;
			address_zip: string;
			country: string;
			name: string;
		}>;
	};
```
ここにemail、 three_d_secureなど渡せるように。あとtenantも渡せるのかな……。

### 3Dセキュアをダイアログで開くメソッド

payjp.openThreeDSecureDialog(objectId: string, timeout: number = 1800000)

などですね。

issue作成後、ご多忙なようで1週間以上お返事がなければ、forkして作成しようかと考えます。

**Comment by nemuvski** [comment]
@araera111 反応が遅れ、大変申し訳ございません。issueとPRありがとうございます！確認させていただきます！

**Comment by nemuvski** [comment]
PRマージさせていただきました。 🙏

**Comment by nemuvski** [comment]
@araera111 
v1.2.0 のリリースに含めさせていただきました！
コミットいただきありがとうございます 🙇
https://github.com/nemuvski/typedef-payjp-js/releases/tag/v1.2.0
